safe: true
pygments: true
auto: true
com: "Seven's Blog"
name: "Seven's Blog"
description: "Seven's Blog"
url: "http://www.dujinfang.com"

# markdown: rdiscount
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
